let
    Source = Csv.Document(
        File.Contents("D:\OneDrive - Goengineer Inc\Documents\Manufacturing-TREID-LAP\Data Analytics\Reports\Customer Segementation\data\processed\icp_scored_accounts.csv"),
        [Delimiter=",", Columns=300, Encoding=1252, QuoteStyle=QuoteStyle.Csv]
    ),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    AllCols = Table.ColumnNames(PromotedHeaders),
    TypeMap = {
        {"Customer ID", Int64.Type},
        {"Company Name", type text},
        {"activity_segment", type text},
        {"am_sales_rep", type text},
        {"AM_Territory", type text},
        {"edu_assets", type text},
        {"RP_Primary_Name", type text},
        {"RP_Primary_Email", type text},
        {"RP_Primary_Phone", type text},
        {"Primary_Contact_Name", type text},
        {"Primary_Contact_Email", type text},
        {"Primary_Contact_Phone", type text},
        {"Name", type text},
        {"email", type text},
        {"phone", type text},
        {"ShippingAddr1", type text},
        {"ShippingAddr2", type text},
        {"ShippingCity", type text},
        {"ShippingState", type text},
        {"ShippingZip", type text},
        {"ShippingCountry", type text},
        {"ICP_score_hardware", type number},
        {"ICP_grade_hardware", type text},
        {"ICP_score_cre", type number},
        {"ICP_grade_cre", type text},
        {"Industry", type text},
        {"Industry Sub List", type text},
        {"Industry_Reasoning", type text},
        {"Hardware_score", type number},
        {"Software_score", type number},
        {"GP_PrevQ_Total", type number},
        {"GP_QoQ_Growth", type number},
        {"GP_T4Q_Total", type number},
        {"GP_Since_2023_Total", type number},
        {"Qty_Printers", Int64.Type},
        {"GP_Printers", type number},
        {"Qty_Printers_AM_Software", Int64.Type},
        {"GP_Printers_AM_Software", type number},
        {"Qty_Printers_AM_Support", Int64.Type},
        {"GP_Printers_AM_Support", type number},
        {"Qty_Printers_Consumables", Int64.Type},
        {"GP_Printers_Consumables", type number},
        {"Qty_Printers_FDM", Int64.Type},
        {"GP_Printers_FDM", type number},
        {"Qty_Printers_FormLabs", Int64.Type},
        {"GP_Printers_FormLabs", type number},
        {"Qty_Printers_Metals", Int64.Type},
        {"GP_Printers_Metals", type number},
        {"Qty_Printers_P3", Int64.Type},
        {"GP_Printers_P3", type number},
        {"Qty_Printers_Polyjet", Int64.Type},
        {"GP_Printers_Polyjet", type number},
        {"Qty_Printers_Post_Processing", Int64.Type},
        {"GP_Printers_Post_Processing", type number},
        {"Qty_Printers_SAF", Int64.Type},
        {"GP_Printers_SAF", type number},
        {"Qty_Printers_SLA", Int64.Type},
        {"GP_Printers_SLA", type number},
        {"Qty_Printers_Spare_Parts_Repair_Parts_Time_and_Materials", Int64.Type},
        {"GP_Printers_Spare_Parts_Repair_Parts_Time_and_Materials", type number},
        {"Qty_Printer Accessories", Int64.Type},
        {"GP_Printer Accessories", type number},
        {"Qty_Scanners", Int64.Type},
        {"GP_Scanners", type number},
        {"Qty_Geomagic", Int64.Type},
        {"GP_Geomagic", type number},
        {"Seats_CAD", Int64.Type},
        {"GP_CAD", type number},
        {"Seats_CPE", Int64.Type},
        {"GP_CPE", type number},
        {"Seats_Specialty Software", Int64.Type},
        {"GP_Specialty Software", type number},
        {"GP_Training/Services_Success_Plan", type number},
        {"GP_Training/Services_Training", type number},
        {"cre_adoption_assets", type number},
        {"cre_adoption_profit", type number},
        {"cre_relationship_profit", type number},
        {"scaling_flag", Int64.Type},
        {"Total Software License Revenue", type number},
        {"active_assets_total", Int64.Type},
        {"seats_sum_total", Int64.Type},
        {"Portfolio_Breadth", Int64.Type},
        {"EarliestPurchaseDate", type datetime},
        {"LatestPurchaseDate", type datetime},
        {"LatestExpirationDate", type datetime},
        {"Days_Since_First_Purchase", Int64.Type},
        {"Days_Since_Last_Purchase", Int64.Type},
        {"Days_Since_Last_Expiration", Int64.Type},
        {"spend_13w", type number},
        {"spend_13w_prior", type number},
        {"delta_13w", type number},
        {"delta_13w_pct", type number},
        {"spend_12m", type number},
        {"spend_52w", type number},
        {"yoy_13w_pct", type number},
        {"days_since_last_order", Int64.Type},
        {"active_weeks_13w", Int64.Type},
        {"purchase_streak_months", Int64.Type},
        {"median_interpurchase_days", Int64.Type},
        {"slope_13w", type number},
        {"slope_13w_prior", type number},
        {"acceleration_13w", type number},
        {"volatility_13w", type number},
        {"seasonality_factor_13w", type number},
        {"trend_score", type number},
        {"recency_score", type number},
        {"magnitude_score", type number},
        {"cadence_score", type number},
        {"momentum_score", type number},
        {"w_trend", type number},
        {"w_recency", type number},
        {"w_magnitude", type number},
        {"w_cadence", type number},
        {"hw_spend_12m", type number},
        {"sw_spend_12m", type number},
        {"hw_share_12m", type number},
        {"sw_share_12m", type number},
        {"breadth_hw_subdiv_12m", type number},
        {"max_hw_subdiv", type number},
        {"breadth_score_hw", type number},
        {"recency_score_hw", type number},
        {"hardware_adoption_score", type number},
        {"consumables_to_hw_ratio", type number},
        {"top_subdivision_12m", type text},
        {"days_since_last_hw_order", Int64.Type},
        {"top_subdivision_share_12m", type number},
        {"discount_pct", type number},
        {"month_conc_hhi_12m", type number},
        {"sw_dominance_score", type number},
        {"sw_to_hw_whitespace_score", type number},
        {"as_of_date", type date},
        {"run_timestamp_utc", type datetime},
        {"spend_13w_printers", type number},
        {"spend_13w_prior_printers", type number},
        {"delta_13w_printers", type number},
        {"delta_13w_pct_printers", type number},
        {"spend_12m_printers", type number},
        {"spend_52w_printers", type number},
        {"yoy_13w_pct_printers", type number},
        {"slope_13w_printers", type number},
        {"slope_13w_prior_printers", type number},
        {"acceleration_13w_printers", type number},
        {"volatility_13w_printers", type number},
        {"seasonality_factor_13w_printers", type number},
        {"days_since_last_order_printers", Int64.Type},
        {"active_weeks_13w_printers", Int64.Type},
        {"spend_12m_pctl", type number},
        {"spend_13w_pctl", type number},
        {"delta_13w_pct_pctl", type number},
        {"yoy_13w_pct_pctl", type number},
        {"slope_13w_pctl", type number},
        {"acceleration_13w_pctl", type number},
        {"acceleration_13w_printers_pctl", type number},
        {"hw_spend_12m_pctl", type number},
        {"sw_spend_12m_pctl", type number},
        {"hw_share_12m_pctl", type number},
        {"sw_share_12m_pctl", type number},
        {"hardware_adoption_score_pctl", type number},
        {"month_conc_hhi_12m_pctl", type number},
        {"sw_dominance_score_pctl", type number},
        {"sw_to_hw_whitespace_score_pctl", type number}
    },
    TypesToApply = List.Select(TypeMap, each List.Contains(AllCols, _{0})),
    ChangedType = Table.TransformColumnTypes(PromotedHeaders, TypesToApply, "en-US"),
    AddedNSUrl = Table.AddColumn(ChangedType, "NS_url", each "https://473193.app.netsuite.com/app/common/entity/custjob.nl?id=" & Number.ToText([Customer ID], "0")),
    AddedEmailAM = Table.AddColumn(AddedNSUrl, "Email Link AM Primary", each if [RP_Primary_Email] = null or Text.PositionOf([RP_Primary_Email], "@") = -1 then null else "mailto:" & [RP_Primary_Email]),
    AddedEmailAcct = Table.AddColumn(AddedEmailAM, "Email Link Account Primary", each if [Primary_Contact_Email] = null or Text.PositionOf([Primary_Contact_Email], "@") = -1 then null else "mailto:" & [Primary_Contact_Email])
in
    AddedEmailAcct

